services:
  app:
    image: star-dust:dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    environment:
      DATABASE_DSN: postgresql+asyncpg://star-dust:password@database:5432/star-dust
      MIGRATIONS: "true"
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_USER: ${SMTP_USER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SENDER_EMAIL_ADDRESS: ${SENDER_EMAIL_ADDRESS}
      SENDER_EMAIL_NAME: ${SENDER_EMAIL_NAME}
      SERVER_HOST: ${SERVER_HOST}

    ports:
      - 8081:8080
    depends_on:
      - database
    volumes:
      - ./star_dust:/home/star-dust/star_dust

  database:
    image: postgres:14.2
    ports:
      - 54042:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=star-dust
    volumes:
      - persistent_db:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:0.14
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=1
      - SERVICES=ses,kinesis
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  persistent_db:
