"""Account autoincrement

Revision ID: 77acfb619627
Revises: c9d64e4d9976
Create Date: 2022-06-28 21:22:41.527335

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "77acfb619627"
down_revision = "c9d64e4d9976"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
