on:
  push:
    branches:
      - master

jobs:
  call-workflow:
    uses: ./.github/workflows/tests.yml

  test-and-lint:
    runs-on: ubuntu-latest
    needs: call-workflow
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: star-dust
        ports:
          - 54042:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: pytest
      - run: black . --check
      - run: mypy star_dust tests --ignore-missing-imports
